### ISSUE TITLE
Sickrage not restarting after upgrade

### ISSUE THREAD

**Issue by wuftymerguftyguff** [binhex/arch-sickrage#4]
Error is
h-4.4# /usr/sbin/python2 /opt/sickrage/SickBeard.py --config /config/config.ini --datadir /config
Traceback (most recent call last):
  File "/opt/sickrage/sickrage/__init__.py", line 266, in main
    from sickrage import core
  File "/opt/sickrage/sickrage/core/__init__.py", line 34, in <module>
    from apscheduler.schedulers.tornado import TornadoScheduler
ImportError: No module named apscheduler.schedulers.tornado
Failed to import required libs, please run 'pip install -r /opt/sickrage/requirements.txt' from console

contents of requirements file seems v old.

**Comment by drezdun** [comment]
same error here.  was working fine yesterday.  made no changes on my end and now it wont start giving error:


2018-10-10 16:34:51.416038 [info] System information Linux b2bd605caf56 4.18.10-unRAID #2 SMP Wed Sep 26 13:21:57 PDT 2018 x86_64 GNU/Linux
2018-10-10 16:34:51.476304 [info] PUID defined as '99'
2018-10-10 16:34:51.573913 [info] PGID defined as '100'
2018-10-10 16:34:51.660763 [info] UMASK defined as '000'
2018-10-10 16:34:51.709560 [info] Permissions already set for volume mappings
2018-10-10 16:34:51.819043 [info] Starting Supervisor...
2018-10-10 16:34:52,482 INFO Included extra file "/etc/supervisor/conf.d/sickrage.conf" during parsing
2018-10-10 16:34:52,483 INFO Set uid to user 0 succeeded
2018-10-10 16:34:52,487 INFO supervisord started with pid 8
2018-10-10 16:34:53,492 INFO spawned: 'sickrage' with pid 48
2018-10-10 16:34:53,493 INFO reaped unknown pid 9
2018-10-10 16:34:53,642 DEBG 'sickrage' stderr output:
Traceback (most recent call last):
File "/opt/sickrage/sickrage/__init__.py", line 266, in main

2018-10-10 16:34:53,642 DEBG 'sickrage' stderr output:
from sickrage import core
File "/opt/sickrage/sickrage/core/__init__.py", line 34, in <module>
from apscheduler.schedulers.tornado import TornadoScheduler
ImportError: No module named apscheduler.schedulers.tornado

2018-10-10 16:34:53,650 DEBG 'sickrage' stdout output:
Failed to import required libs, please run 'pip install -r /opt/sickrage/requirements.txt' from console

**Comment by exotian** [comment]
same error here, i just noticed that my shows aren't downloading any more, worked fine 2 days ago, now throws this error.

Created by...
___. .__ .__
\_ |__ |__| ____ | |__ ____ ___ ___
| __ \| |/ \| | \_/ __ \\ \/ /
| \_\ \ | | \ Y \ ___/ > <
|___ /__|___| /___| /\___ >__/\_ \
\/ \/ \/ \/ \/
https://hub.docker.com/u/binhex/

2018-10-10 21:47:11.228657 [info] System information Linux ea685ff68688 4.18.8-unRAID #1 SMP Sat Sep 15 09:15:50 PDT 2018 x86_64 GNU/Linux
2018-10-10 21:47:11.260488 [info] PUID defined as '99'
2018-10-10 21:47:11.308628 [info] PGID defined as '100'
2018-10-10 21:47:11.352413 [info] UMASK defined as '000'
2018-10-10 21:47:11.382174 [info] Permissions already set for volume mappings
2018-10-10 21:47:11.441936 [info] Starting Supervisor...
2018-10-10 21:47:11,826 INFO Included extra file "/etc/supervisor/conf.d/sickrage.conf" during parsing
2018-10-10 21:47:11,826 INFO Set uid to user 0 succeeded
2018-10-10 21:47:11,828 INFO supervisord started with pid 8
2018-10-10 21:47:12,830 INFO spawned: 'sickrage' with pid 48
2018-10-10 21:47:12,831 INFO reaped unknown pid 9
2018-10-10 21:47:12,920 DEBG 'sickrage' stderr output:
Traceback (most recent call last):
File "/opt/sickrage/sickrage/__init__.py", line 266, in main

2018-10-10 21:47:12,920 DEBG 'sickrage' stderr output:
from sickrage import core
File "/opt/sickrage/sickrage/core/__init__.py", line 34, in <module>
from apscheduler.schedulers.tornado import TornadoScheduler
ImportError: No module named apscheduler.schedulers.tornado

2018-10-10 21:47:12,925 DEBG 'sickrage' stdout output:
Failed to import required libs, please run 'pip install -r /opt/sickrage/requirements.txt' from console


2018-10-10 21:47:12,926 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 23014237737184 for <Subprocess at 23014237737400 with name sickrage in state STARTING> (stdout)>
2018-10-10 21:47:12,926 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 23014237740928 for <Subprocess at 23014237737400 with name sickrage in state STARTING> (stderr)>
2018-10-10 21:47:12,926 INFO exited: sickrage (exit status 0; not expected)
2018-10-10 21:47:12,926 DEBG received SIGCLD indicating a child quit
2018-10-10 21:47:13,929 INFO spawned: 'sickrage' with pid 50
2018-10-10 21:47:14,007 DEBG 'sickrage' stderr output:
Traceback (most recent call last):
File "/opt/sickrage/sickrage/__init__.py", line 266, in main

2018-10-10 21:47:14,007 DEBG 'sickrage' stderr output:
from sickrage import core
File "/opt/sickrage/sickrage/core/__init__.py", line 34, in <module>
from apscheduler.schedulers.tornado import TornadoScheduler
ImportError: No module named apscheduler.schedulers.tornado

2018-10-10 21:47:14,012 DEBG 'sickrage' stdout output:
Failed to import required libs, please run 'pip install -r /opt/sickrage/requirements.txt' from console


2018-10-10 21:47:14,013 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 23014299799208 for <Subprocess at 23014237737400 with name sickrage in state STARTING> (stdout)>
2018-10-10 21:47:14,013 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 23014238052432 for <Subprocess at 23014237737400 with name sickrage in state STARTING> (stderr)>
2018-10-10 21:47:14,013 INFO exited: sickrage (exit status 0; not expected)
2018-10-10 21:47:14,013 DEBG received SIGCLD indicating a child quit
2018-10-10 21:47:16,015 INFO spawned: 'sickrage' with pid 52
2018-10-10 21:47:16,094 DEBG 'sickrage' stderr output:
Traceback (most recent call last):
File "/opt/sickrage/sickrage/__init__.py", line 266, in main

2018-10-10 21:47:16,094 DEBG 'sickrage' stderr output:
from sickrage import core
File "/opt/sickrage/sickrage/core/__init__.py", line 34, in <module>
from apscheduler.schedulers.tornado import TornadoScheduler
ImportError: No module named apscheduler.schedulers.tornado

2018-10-10 21:47:16,098 DEBG 'sickrage' stdout output:
Failed to import required libs, please run 'pip install -r /opt/sickrage/requirements.txt' from console


2018-10-10 21:47:16,099 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 23014299799208 for <Subprocess at 23014237737400 with name sickrage in state STARTING> (stdout)>
2018-10-10 21:47:16,099 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 23014299874584 for <Subprocess at 23014237737400 with name sickrage in state STARTING> (stderr)>
2018-10-10 21:47:16,099 INFO exited: sickrage (exit status 0; not expected)
2018-10-10 21:47:16,100 DEBG received SIGCLD indicating a child quit
2018-10-10 21:47:19,103 INFO spawned: 'sickrage' with pid 54
2018-10-10 21:47:19,188 DEBG 'sickrage' stderr output:
Traceback (most recent call last):
File "/opt/sickrage/sickrage/__init__.py", line 266, in main

2018-10-10 21:47:19,188 DEBG 'sickrage' stderr output:
from sickrage import core
File "/opt/sickrage/sickrage/core/__init__.py", line 34, in <module>
from apscheduler.schedulers.tornado import TornadoScheduler
ImportError: No module named apscheduler.schedulers.tornado

2018-10-10 21:47:19,193 DEBG 'sickrage' stdout output:
Failed to import required libs, please run 'pip install -r /opt/sickrage/requirements.txt' from console


2018-10-10 21:47:19,194 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 23014299799208 for <Subprocess at 23014237737400 with name sickrage in state STARTING> (stdout)>
2018-10-10 21:47:19,194 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 23014237737688 for <Subprocess at 23014237737400 with name sickrage in state STARTING> (stderr)>
2018-10-10 21:47:19,194 INFO exited: sickrage (exit status 0; not expected)
2018-10-10 21:47:19,194 DEBG received SIGCLD indicating a child quit
2018-10-10 21:47:20,194 INFO gave up: sickrage entered FATAL state, too many start retries too quickly

**Comment by drezdun** [comment]
Looking like just a bad update push. (regular release of sickrage still working) so hopefully this can all be sorted with just an OTA update push for binhex-sickrage

**Comment by drezdun** [comment]
Still nothing on this? Have either of you two found a solution?

**Comment by wuftymerguftyguff** [comment]
Still an issue, no solution I can see.

Anyone know if this works?

https://hub.docker.com/r/sickrage/sickrage/

**Comment by drezdun** [comment]
hey guys.  For a temporary work around while binhex fixes current release (he says he is on it over on the unraid forums) 

Edit the SickRage container and in the repository line change it binhex/arch-sickrage:latest to binhex/arch-sickrage:v2018.10.06-1-01 and hit save.  You'll have to manually remove the orphan from your docker tab. ﻿

for clarity my repository line had binhex/arch-sickrage in it, changing it to binhex/arch-sickrage:v2018.10.06-1-01 rolled back the install and at least allows sickrage to run and fetch shows while we wait for binhex to fix current release.

**Comment by binhex** [comment]
fixed up guys, but PLEASE read my post in full before you consider updating:-

https://forums.unraid.net/topic/44144-support-binhex-sickrage/?do=findComment&comment=690022
